### ISSUE TITLE
Option to use logical properties

### ISSUE THREAD

**Issue by equinusocio** [csstools/postcss-inset#1]
Hello! I think it could be useful an option to use logical properties instead of classic ones. For example, with this option set to true, the conversion would be:

```css
div {
	inset: 0 300px 200px 100px;
}

/* Output */    

div {
	inset-block-start: 0;
	inset-inline-end: 300px;
 	inset-block-end: 200px;
	inset-inline-start: 100px;
}

/* or both */


div {
	top: 0;
	right: 300px;
    bottom: 200px;
	left: 100px;
	inset-block-start: 0;
	inset-inline-end: 300px;
 	inset-block-end: 200px;
	inset-inline-start: 100px;
}
```

Logical properties are now well supported and they are a real option.
